// Generated by ReScript, PLEASE EDIT WITH CARE


var textView = document.getElementById("textView");

function updateView($$event) {
  textView.innerText = $$event.target.value;
  
}

var textEditor = document.getElementById("textEditor");

textEditor.addEventListener("input", updateView);

var selectSmall = document.getElementById("selectSmall");

var selectLarge = document.getElementById("selectLarge");

var selectRegular = document.getElementById("selectRegular");

selectSmall.addEventListener("change", (function (param) {
        textView.classList.add("text-sm");
        return textView.classList.remove("text-2xl", "text-6xl");
      }));

selectRegular.addEventListener("change", (function (param) {
        textView.classList.add("text-2xl");
        return textView.classList.remove("text-sm", "text-6xl");
      }));

selectLarge.addEventListener("change", (function (param) {
        textView.classList.add("text-6xl");
        return textView.classList.remove("text-sm", "text-2xl");
      }));

export {
  textView ,
  updateView ,
  textEditor ,
  selectSmall ,
  selectLarge ,
  selectRegular ,
  
}
/* textView Not a pure module */
